### ISSUE TITLE
Better Outfitters/Hire Button Controls

### ISSUE THREAD

**Issue by codejp3** [thewierdnut/endless-mobile#48] opened 2023-02-24 03:21 UTC
### Problem Description

One thing that would save tons of time and prevent frustrations is better button control handling for bulk actions - sell, buy, hire and so on. Anything dealing with numbers and repeat actions.

### Related Issue Links

none

### Desired Solution

SUGGESTION 1: tap once and hold the button to bulk buy/sell/hire the maximum amount possible. 

### Alternative Approaches

SUGGESTION 2: tap once and hold to popup a input box where you can type/select the quantity to buy/sell/hire.

### Additional Context

Either approach should apply to anything dealing with quantity and bulk actions (buy/sell/hire).

REASON: An example is that I keep collecting gattling gun ammo faster than I can sell it. Thousands at a time. To the point that I sell batches of 100 everytime I hit an outfitter, but it keeps piling up by the thousands. If I want to get rid of 10,000 rounds of ammo, I have to hit sell 10,000 times. Even when I do, it still keeps collecting so I have to repeat it over and over. I've probably tapped "sell" 100,000 times of more, just for gattling gun ammo, not to mention other items. A ton of wasted time, unnecessary frustrations, and sore fingers from tapping so much.

**Comment by thewierdnut** [comment] 2023-02-24 13:46
There are new dropdowns as of build 31 on the outfitter page. 

Also, keep in mind that there is a "sell all outfits" button on the trading panel if you have outfits in your cargo.

**Comment by thewierdnut** [comment] 2023-02-24 13:46
Duplicate of #36

**Comment by codejp3** [comment] 2023-02-24 16:09
I know you marked this as closed/no plans to implement, but I'd like to encourage you to reconsider.

REASON: unnecessary clicks for common repeat actions. 

ANOTHER EXAMPLE: I capture ships regularly. Taking better ships is part of the core gameplay. With that said, as better ships are captured, I change out my primary ship for a better one. That involves:

Tapping "sell" several hundred times for rifles for the old primary ship.

Tapping "sell" several hundred times for hand grenades for the old primary ship.

Tapping "sell" several hundred times for nerve gas for the old primary ship.

Tapping "buy" several hundred times for rifles for the new primary ship.

Tapping "buy" several hundred times for hand grenades for the new primary ship.

Tapping "buy" several hundred times for nerve gas for the new primary ship.

Tapping "hire" several hundred times to fill the new primary ship.

That's easily a thousand+ taps for a regular part of gameplay that could be done in 6-7 taps.

Not to mention, after capturing a new ship, I have to tap "hire" several hundred times even if I don't swap the ship as the new primary. Almost every planet I land on requires hundreds of taps to get straight before departure.

I love the port to Android, but my sore fingers don't!

**Comment by thewierdnut** [comment] 2023-02-24 16:23
Sorry, you misunderstand... this has been fixed already, at least for outfits. If you have upgraded to build 31 or newer, you should be able to access a Quantity dropdown that allows you to select the number to buy or sell. 

![image](https://user-images.githubusercontent.com/9004013/221231942-046a02eb-b549-4bb9-b299-b94ccffac853.png)

**Comment by thewierdnut** [comment] 2023-02-24 16:24
This doesn't fix the Hire Crew panel though... I'll look into that as well.

**Comment by johndh** [comment] 2023-02-25 21:40
> Not to mention, after capturing a new ship, I have to tap "hire" several hundred times even if I don't swap the ship as the new primary. Almost every planet I land on requires hundreds of taps to get straight before departure.
> 
If you're talking about rehiring crew after you've used some of them to capture a ship, there's a setting in the preferences menu that has it automatically refill your crew.

![Screenshot_20230225-153752-704~2](https://user-images.githubusercontent.com/692397/221380780-feb1bfc5-1891-49f8-832a-f977ba5ae5e5.png)

**Comment by codejp3** [comment] 2023-03-02 21:54
Updated to build 31. For some reason F-droid didn't notify me about it. Your solution for outfitter works great and gets the job done.

The auto-hire setting certainly helps and addressed the most common hiring scenario. It would still be nice to have a bulk hire (like outfitter) for when there's a new ship purchased or changed-out, or extra bunks are added in outfitter. Sometimes those scenarios add hundred of new crew spots to hire for.

FYI -build 31 has a slight issue with the table header row alignment in the hire section. I can open a separate support topic for it if you want.
![Screenshot_2023-02-25-09-58-19-47_ea43f885669e671608fc729b354f0fbd](https://user-images.githubusercontent.com/26341487/222566111-6bca5568-a07a-42ba-b221-5f2349f5bcb1.jpg)

**Comment by thewierdnut** [comment] 2023-03-02 21:56
Yeah, I noticed the line alignment thing a few days ago. its already fixed in the continuous build.

**Closed as completed** 2023-03-20 19:04 UTC
