### ISSUE TITLE
Deploy button missing in PR 29

### ISSUE THREAD

**Issue by daisy613** [thewierdnut/endless-mobile#28] opened 2022-12-22 04:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Deploy button missing in PR 29

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

I'm flying Roost with 4 fighters attached, but no Deploy button is available

### Screenshots

![Screenshot_20221221_234347_Endless Sky](https://user-images.githubusercontent.com/8550213/209059479-2cd8d2bc-7f1b-45c7-b8a4-8a8527311ca6.png)

### Device type

Galaxy S20

### Game Version

0.9.16.1 PR v29

**Comment by thewierdnut** [comment] 2022-12-22 05:09
This was fixed in merge #23. There hasn't been a new pre-release since then, although the continuous build should have it.

**Comment by thewierdnut** [comment] 2022-12-22 05:10
Duplicate of #21

**Closed as completed by thewierdnut** 2022-12-22 05:10 UTC
Labels: bug

**Comment by daisy613** [comment] 2022-12-22 05:56
How do I get an apk for the merge or continuous? I'm not savvy enough to run a build...

**Comment by thewierdnut** [comment] 2022-12-22 14:38
I'm assuming you've been running the unsigned pre-release apks instead of the f-droid version. In that case, you can go to the releases page [here](https://github.com/thewierdnut/endless-mobile/releases) click on the link provided in the "Continuous Build". The apk should be listed under "Artifacts" at the bottom of the page. I would provide a direct link, except those artifacts expire after some time, and it would go stale.
