### ISSUE TITLE
Parking Individual Ships

### ISSUE THREAD

**Issue by codejp3** [thewierdnut/endless-mobile#49] opened 2023-02-24 03:26 UTC
### Problem Description

I can park all ships, or I can unpark all ships. But I cannot park/unpark individual Ships like you can in the desktop version.

### Related Issue Links

None

### Desired Solution

Add option to park/unpark individual ships in map>info like the desktop version has.

### Alternative Approaches

none

### Additional Context

Can't speak for everyone, but I never want to park every ship all at once. I only ever want to park selective ships at selective planets, and I can't do that in the android version.

**Comment by thewierdnut** [comment] 2023-02-24 13:49
This is done from the Ship Info tab, not the Player Info tab. Just select the ship you want to park, and as long as it is not your flagship, the Disown and Park buttons will be on the bottom. 

You can also double-tap your ship in the Player Info tab to auto-switch to the Ship Info tab with the proper ship selected

**Comment by thewierdnut** [comment] 2023-02-24 13:50
Duplicate of #29

**Closed as not planned by thewierdnut** 2023-02-24 13:50 UTC

**Comment by codejp3** [comment] 2023-02-24 16:14
Got it. I looked for that, but was on my primary ship so it didn't show. Just verified it is indeed there for non-primary ships. Thanks!
