### ISSUE TITLE
No "attack/mine" button

### ISSUE THREAD

**Issue by Crivium** [thewierdnut/endless-mobile#46] opened 2023-02-16 18:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no button to either fire weapons or mine asteroids, tapping just mpves the ship.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

A buutton in the lower section to fire/mine

### Screenshots

![Screenshot_2023-02-16-19-13-42-07_ea43f885669e671608fc729b354f0fbd](https://user-images.githubusercontent.com/26851621/219453770-c6109e99-7249-484d-9855-ef5e243d5113.jpg)

### Device type

realme 6i

### Game Version

0.9.16.1-30

**Comment by thewierdnut** [comment] 2023-02-16 18:25
If you have a target selected, the Attack button will appear. 

A "mine" button will appear as of commit 8c41e77, which does not have a stable release yet. 

Duplicate of #20

**Closed as completed by thewierdnut** 2023-02-16 18:25 UTC
Labels: bug
