### ISSUE TITLE
No Jobs and Accepted Missions Gone After Closing Via Android App Drawer

### ISSUE THREAD

**Issue by paintchip** [thewierdnut/endless-mobile#42] opened 2023-02-07 18:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you land on a planet at the end of a mission (and maybe sometimes in general) and exit the game, upon returning to the game there are no available missions and any missions you accepted on that planet (before exiting) are gone. This only happens when closing the game through Android and not using the exit button in the main menu. I feel like this is basically "crashing" the game, but it's bound to happen on Android where you can background the game and forget about it. 

Departing the planet and re-landing generates new missions.

### Steps to Reproduce

1. Take a mission and complete it on a planet.
2. Go to the job board and accept a mission (optional).
3. Background the game with the Android back button. 
4. Close the game by swiping it out of the applications list in Android.
5. Return to the game and go to the job board.

### Expected Behavior

I expect that the jobs I saw before backgrounding and closing the game to still be there, especially ones that I accepted.

### Link to save file

![open_sky_bug](https://user-images.githubusercontent.com/9015968/217335358-dc769a83-0f52-46e8-bb03-572e78ddc064.jpg)

### Device type

One Plus Nord N10 5G

### Game Version

0.9.16.1-30

**Comment by thewierdnut** [comment] 2023-02-28 15:33
Duplicate of #39

**Comment by thewierdnut** [comment] 2023-03-20 18:44
This happens when you land, and then close, but not if you depart and then close.

**Closed as completed** 2023-03-20 19:05 UTC
Labels: bug
