### ISSUE TITLE
Preferences don't save

### ISSUE THREAD

**Issue by daisy613** [thewierdnut/endless-mobile#33] opened 2023-01-03 05:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The preferences aren't saved. Every time the game is started, the preferences return to default. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Preferences save.

### Device type

Galaxy S20

### Game Version

0.9.16.1

**Comment by thewierdnut** [comment] 2023-01-03 17:04
Duplicate of #13

**Closed as completed by thewierdnut** 2023-01-03 17:04 UTC
Labels: bug
