### ISSUE TITLE
Previous version saves not showing up

### ISSUE THREAD

**Issue by MushiShirohime** [thewierdnut/endless-mobile#124] opened 2024-02-06 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Went to load up my save after updating and only my previous topmost save was pre-selected and accessible with all of them being hidden/not shown

### Steps to Reproduce

1. Make save on previous version I guess?
2. Update
3. Load save but realize it only shows up on the main menu
4. Groan in frustration

### Expected Behavior

The ability to see all saves

### Device type

Samsung Galaxy S8+

### Game Version

Just updated to latest/Previous version was the directly before the latest

**Comment by thewierdnut** [comment] 2024-02-06 12:36
Duplicate of #123

**Comment by thewierdnut** [comment] 2024-02-06 12:38
This should be fixed in build 41, which f-droid will probably update in a week or so. 

In the meantime, you can work around this by installing the plugin here. Be sure to uninstall the plugin once version 41 comes out:

https://github.com/thewierdnut/endless_mobile_version_40_load_panel_fix/archive/refs/heads/main.zip

**Closed as completed** 2024-02-13 12:26 UTC
Labels: bug
