### ISSUE TITLE
Pilot creation

### ISSUE THREAD

**Issue by Codreanue** [thewierdnut/endless-mobile#11] opened 2022-11-05 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When first starting a new game, it won't allow me to type in a name, leading to me being stuck in the starting text screen. 

### Steps to Reproduce

1. Go to 'main menu'
2. Click on 'start new game'
3. Scroll down to 'frst name/last name'
4. You will see that it will not let you type at all. 

### Expected Behavior

You will be stuck on the introduction screen, having to close the app, you cannot go back to the main menu nor can you progress

### Screenshots

![Screenshot_20221105_133409_Endless Sky](https://user-images.githubusercontent.com/117542904/200140212-8d470f88-595c-4e42-9285-d6feb57fef41.jpg)

https://user-images.githubusercontent.com/117542904/200140305-f7e4e872-b3b1-49bb-9e7d-0c2861357fa7.mp4

### Operating System

Samsung S22, android version 13

### Game Source

Other (please describe)

### Game Version

V0.9.16.1-28

### Additional Information

When sourcing the game I used F-Droid

I will note there was a very recent update the morning of this post which might have affected something, but I'm unaware of any changes that could've created the issue I'm having.

**Comment by thewierdnut** [comment] 2022-11-05 22:44
For some reason, the code that turns on the on screen keyboard only works if you click directly on the text box that *doesn't* already have the focus. This means clicking on the "Last Name" text box (the text box, not the label) right after it loads. Clicking on "Ok" doesn't work, and clicking on "First Name" only works if "Last Name" already has the focus. 

I'll see if I can't make this more intuitive somehow, but I'm limited by the primitive input handling and the SDL interface. 

This is a duplicate of #8

**Closed as not planned by thewierdnut** 2022-11-05 22:44 UTC
Labels: bug

**Comment by thewierdnut** [comment] 2022-11-06 15:37
Duplicate of #8
