### ISSUE TITLE
export / import save file

### ISSUE THREAD

**Issue by blaasrg** [thewierdnut/endless-mobile#16] opened 2022-11-13 21:14 UTC
### Problem Description

I was wondering if you could add a save file exporter and importer option so if you made a huge mistake in the story you could export the save file and edit it then import it or if you just wanted to ruin the fun of the game. Sorry for the bad english.

### Related Issue Links

None that I know of.

### Desired Solution

To have a button in the main or settings menu to export or import the save.

### Alternative Approaches

Or you could also make it automaticaly detect the save file and show it in the list but id recomend you don't because it will probably take more time.

### Additional Context

Sorry if this is too much to ask.

**Comment by thewierdnut** [comment] 2022-11-14 00:16
Duplicate of #6

**Comment by thewierdnut** [comment] 2022-11-14 00:20
There should be import and export buttons on the pilot load/save screen

**Closed as completed** 2022-11-14 00:20 UTC
