### ISSUE TITLE
Add support for importing/exporting save files

### ISSUE THREAD

**Issue by rediris** [thewierdnut/endless-mobile#9] opened 2022-10-20 16:52 UTC
### Problem Description

It would be nice to have the option of accessing the save game .txt files - whether to import or export. There's currently no way of accessing those files in android without rooting one's phone.

### Related Issue Links

N/A.

### Desired Solution

* Save game file would be accessible in Android's files app (internal storage)
* The in app menu would have an option to import and export save game files

### Alternative Approaches

N/A

**Comment by thewierdnut** [comment] 2022-10-20 16:55
Duplicate of #6 

Presumably this will get updated on f-droid eventually.

**Closed as not planned** 2022-10-20 16:57 UTC

**Comment by thewierdnut** [comment] 2022-11-06 15:38
Duplicate of #6
